xfce-build: Add error for build failure

diff --git a/helpers/xfce-build b/helpers/xfce-build
--- a/helpers/xfce-build
+++ b/helpers/xfce-build
@@ -21,6 +21,12 @@ docker_run () {
 	# Run the build in the docker container
 	# That z parameter for volume is needed when SELinux is enabled
 	docker run --rm -u $(id -u ${USER}):$(id -g ${USER}) --volume $VOLUME:/tmp:z --env CFLAGS="${CFLAGS}" --env CONTAINER=$CONTAINER --env VERSION=$VERSION $CONTAINER:$VERSION /bin/bash -c "${BUILD_CMD}"
+	value=$?
+	if ((value != 0)); then
+		printf "\n---\nError building %s\n" "${VOLUME##*/}"
+		return $value
+	fi
+	printf "\n---\nBuilt using container $CONTAINER:$VERSION on $VOLUME\n"
 }
 
 # Parse the commandline arguments
@@ -31,7 +37,7 @@ elif [[ "$1" == "pull" ]]; then
 	exit 0
 elif [[ "$1" == "describe" ]]; then
 	if [[ ! -z "$2" ]]; then
-			VERSION="$2"
+		VERSION="$2"
 	fi
 	BUILD_CMD='printf "\e[1m$CONTAINER:$VERSION contains:\e[0m\n";cat /git/xfce_build_version_info.txt'
 	docker_run
@@ -41,4 +47,4 @@ fi
 # Run the local build
 docker_pull
 docker_run
-printf "\n---\nBuilt using container $CONTAINER:$VERSION on $VOLUME\n"
+exit $?
