Add meson support to xfce-do-release

diff --git a/helpers/xfce-do-release.in b/helpers/xfce-do-release.in
--- a/helpers/xfce-do-release.in
+++ b/helpers/xfce-do-release.in
@@ -14,6 +14,7 @@ nproc=$( \
 
 SED=${SED:-@GSED@}
 MAKE=${MAKE:-@GMAKE@}
+MESON=${MESON:-@MESON@}
 
 # Check if the working directory is in the state we expect it to be in
 sanity_checks () {
@@ -148,12 +149,17 @@ run_command () {
 	read -n 1 -p " → Do it? ([y]es, [N]o, [s]kip) " response
 	printf "\n"
 	if [ "$response" = "y" ]; then
-		eval $1 && eval $2 && eval $3
-		printf "\n ✓ Done."
-		let steps_complete++
+		if eval $1 && eval $2 && eval $3; then
+			printf "\n ✓ Done."
+			let steps_complete++
+			return 0
+		else
+			printf "\n × Failed!"
+			return 1
+		fi
 	elif [ "$response" = "s" ]; then
 		printf "\n Step $(( $steps - 1 )) skipped."
-		return
+		return 0
 	else
 		read -n 1 -p " Step $(( $steps - 1 )) aborted. Do you really want to quit? ([y]es, [N]o) " abort
 		if [ "$abort" = "y" ]; then
@@ -161,8 +167,19 @@ run_command () {
 			exit 0
 		else
 			printf "\n Step $(( $steps - 1 )) aborted. Continuing...\n"
-			return
+			return 0
 		fi
+	fi
+}
+
+build_system_type () {
+	if [ -f "configure.ac" -o -f "configure.ac.in" ]; then
+		echo "autotools"
+	elif [ -f "meson.build" ]; then
+		echo "meson"
+	else
+		printf "$warning Unknown build system.\n"
+		return 1
 	fi
 }
 
@@ -197,57 +214,101 @@ edit () {
 	fi
 }
 
-update_configure_ac_in () {
+update_project_version () {
 	local configure_file
+	local meson_build_file
 
 	if [ -f "configure.ac.in" ]; then
 		configure_file="configure.ac.in"
 	elif [ -f "configure.ac" ]; then
 		configure_file="configure.ac"
-	else
-		printf "$warning There is no 'configure.ac.in' or 'configure.ac' file.\n"
+	fi
+
+	if [ -f "meson.build" ]; then
+		meson_build_file="meson.build"
+	fi
+
+	if [ -z "$configure_file" -a -z "$meson_build_file" ]; then
+		printf "$warning There is no 'configure.ac.in', 'configure.ac', or 'meson.build' file.\n"
 		return 1
 	fi
 
-	if ! grep -zq "AC_COPYRIGHT(\[[^]]*$(date +%Y)[^]]*\])" "$configure_file"; then
-		printf '%b\n' \
-			"\n$warning The copyright year of the project does not seem to be up to date." \
-			"This is just a check of '$configure_file' though, you should check this in the" \
-			"whole source code, especially the about dialog and/or its command line counterpart.\n"
+	if [ "$configure_file" ]; then
+		if ! grep -zq "AC_COPYRIGHT(\[[^]]*$(date +%Y)[^]]*\])" "$configure_file"; then
+			printf '%b\n' \
+				"\n$warning The copyright year of the project does not seem to be up to date." \
+				"This is just a check of '$configure_file' though, you should check this in the" \
+				"whole source code, especially the about dialog and/or its command line counterpart.\n"
+		fi
+
+		if grep -q 'XDT_VERSION_INIT' "$configure_file"; then
+			if [ "$1" = "pre" ]; then
+				$SED -i "s/^\(XDT_VERSION_INIT\s*\)(.*/\1([$version])/" "$configure_file"
+			elif [ "$1" = "post" ]; then
+				$SED -i "s/^\(XDT_VERSION_INIT\s*\)(.*/\1([$version], [git])/" "$configure_file"
+			fi
+		else
+			if [ "$1" = "pre" ]; then
+				$SED -i \
+					-e "s/^\(m4_define(\[.*_version_major\], *\[\)\(.*\)\(\])\)/\1$version_major\3/g" \
+					-e "s/^\(m4_define(\[.*_version_minor\], *\[\)\(.*\)\(\])\)/\1$version_minor\3/g" \
+					-e "s/^\(m4_define(\[.*_version_micro\], *\[\)\(.*\)\(\])\)/\1$version_patch\3/g" \
+					-e 's/^\(m4_define(\[.*_version_tag\], *\[\)\(git\)\(\])\)/\1\3/g' \
+					"$configure_file"
+			elif [ "$1" = "post" ]; then
+				$SED -i 's/\(m4_define(\[.*_version_tag\], *\[\)\(.*\)\(\])\)/\1git\3/g' "$configure_file"
+			fi
+		fi
 	fi
 
-	if grep -q 'XDT_VERSION_INIT' "$configure_file"; then
-		if [ "$1" = "pre" ]; then
-			$SED -i "s/^\(XDT_VERSION_INIT\s*\)(.*/\1([$version])/" "$configure_file"
-		elif [ "$1" = "post" ]; then
-			$SED -i "s/^\(XDT_VERSION_INIT\s*\)(.*/\1([$version], [git])/" "$configure_file"
+	if [ "$meson_build_file" ]; then
+		local meson_version_string
+
+		meson_version_string="$version_major.$version_minor.$version_patch"
+		if [ "$1" = "post" ]; then
+			meson_version_string+="-dev"
 		fi
-	else
-		if [ "$1" = "pre" ]; then
-			$SED -i \
-				-e "s/^\(m4_define(\[.*_version_major\], *\[\)\(.*\)\(\])\)/\1$version_major\3/g" \
-				-e "s/^\(m4_define(\[.*_version_minor\], *\[\)\(.*\)\(\])\)/\1$version_minor\3/g" \
-				-e "s/^\(m4_define(\[.*_version_micro\], *\[\)\(.*\)\(\])\)/\1$version_patch\3/g" \
-				-e 's/^\(m4_define(\[.*_version_tag\], *\[\)\(git\)\(\])\)/\1\3/g' \
-				"$configure_file"
-		elif [ "$1" = "post" ]; then
-			$SED -i 's/\(m4_define(\[.*_version_tag\], *\[\)\(.*\)\(\])\)/\1git\3/g' "$configure_file"
-		fi
+
+		$MESON rewrite kwargs set project / version "$meson_version_string"
 	fi
 
-	if git diff --exit-code "$configure_file"; then
-		printf "$warning No change made to $configure_file, probably a file format issue.\n"
+	if git diff --exit-code "$configure_file" "$meson_build_file"; then
+		printf "$warning No project version change, probably a file format issue.\n"
 	fi
 }
 
 get_sha1_hash () {
-	sha1sum $component-$version.tar.bz2 | cut -d ' ' -f 1
+	local suffix
+
+	if [ "$1" = "autotools" ]; then
+		suffix=bz2
+	elif [ "$1" = "meson" ]; then
+		suffix=xz
+	fi
+
+	sha1sum "$component-$version.tar.$suffix" | cut -d ' ' -f 1
+}
+
+join_by () {
+	local delim="${1-}" first="${2-}"
+	if shift 2; then
+		printf '%s' "$first" "${@/#/$delim}"
+	fi
 }
 
 # Playbook for all release steps
 run_steps () {
-	step "Update configure.ac.in \e[0m(add new version and remove git tag)"
-	run_command "update_configure_ac_in pre"
+	local build_type
+	local dist_commands
+	local build_tarball_prompt
+
+	build_type=$(build_system_type)
+	if [ -z "$build_type" ]; then
+		return 1
+	fi
+
+	step "Update project version \e[0m(add new version and remove git tag)"
+	run_command "update_project_version pre"
 
 	step "Update NEWS file with changelog? \e[0m(xfce-update-news)"
 	run_command "xfce-update-news $component $version"
@@ -258,23 +319,37 @@ run_steps () {
 		run_command "update_appdata_file $appdata_file"
 	fi
 
-	step "Build the tarball \e[0m(./autogen.sh && $MAKE -j$nproc distcheck)"
-	# either in the xfce-build or xfce-test container or on the local machine
-	if [ -n "$TAG" ]; then
-		if [[ "$TAG" == "xfce-build" ]]; then
-			run_command "xfce-build"
-		else
-			run_command "xfce-test call ./autogen.sh" "xfce-test call $MAKE -j$nproc distcheck"
-		fi
-	else
-		run_command "./autogen.sh" "$MAKE -j$nproc distcheck"
-	fi
-
 	step "Commit the changes \e[0m(git add -u; git commit -m 'Updates for release')"
 	run_command "git add -u" "git commit -m 'Updates for release'"
 
 	step "Tag the version \e[0m(git tag -a $component-$version)"
 	run_command 'git tag -a $component-$version -e -m "$(xfce-update-news $component $version WRITETAG)"'
+
+	if [ "$build_type" = "autotools" ]; then
+		build_tarball_prompt="Build the tarball \e[0m(./autogen.sh && $MAKE -j$nproc distcheck)"
+		dist_commands=("./autogen.sh" "$MAKE -j$nproc distcheck")
+	elif [ "$build_type" = "meson" ]; then
+		build_tarball_prompt="Build the tarball \e[0m(meson setup && meson dist)"
+		dist_commands=("rm -rf build" "meson setup build" "meson dist -C build --include-subprojects")
+	fi
+
+	# either in the xfce-build or xfce-test container or on the local machine
+	if [[ "$TAG" == "xfce-build" ]]; then
+		# turn the array into a single argument to pass to 'xfce-build',
+		# stripping any '-j' arguments
+		dist_commands=("xfce-build $(join_by ' \&\& ' "${dist_commands[@]}" | sed -e 's/-j[0-9]*//')")
+	elif [ -n "$TAG" ]; then
+		# prefix each element with 'xfce-test call '
+		dist_commands=("${dist_commands[@]/#/xfce-test call }")
+	fi
+
+	step "$build_tarball_prompt"
+	if ! run_command "${dist_commands[@]}"; then
+		printf "\n\nDeleting tag and rolling back release commit.\n"
+		git tag -d $component-$version
+		git reset --hard HEAD^
+		return 1
+	fi
 
 	step "Push your changes \e[0m(git push && git push --tags)"
 	run_command "git push" "git push --tags"
@@ -283,10 +358,10 @@ run_steps () {
 	run_command "exo-open 'https://releases.xfce.org/'"
 
 	step "Click on 'Release New Version' \e[0m(https://releases.xfce.org/project/$component/new-release/tarball)"
-	run_command "exo-open 'https://releases.xfce.org/project/$component/new-release/tarball?checksum=$(get_sha1_hash)'"
+	run_command "exo-open 'https://releases.xfce.org/project/$component/new-release/tarball?checksum=$(get_sha1_hash $build_type)'"
 
-	step "Add the git back to version_tag() in configure.ac.in"
-	run_command "update_configure_ac_in post"
+	step "Post-update project version \e[0m(add back git tag)"
+	run_command "update_project_version post"
 
 	step "Commit and push the change \e[0m(git add -u; git commit -m 'Back to development'; git push)"
 	run_command "git add -u" "git commit -m 'Back to development'" "git push"
@@ -297,7 +372,7 @@ run_steps () {
 main () {
 	sanity_checks
 	test_parameters $component $version
-	run_steps
+	run_steps || exit 1
 
 	printf "\nCongrats, you completed $steps_complete of $steps steps of doing a release for Xfce!\n"
 }
