Add meson support to xfce-do-release

diff --git a/helpers/xfce-do-release.in b/helpers/xfce-do-release.in
--- a/helpers/xfce-do-release.in
+++ b/helpers/xfce-do-release.in
@@ -148,12 +148,17 @@ run_command () {
 	read -n 1 -p " → Do it? ([y]es, [N]o, [s]kip) " response
 	printf "\n"
 	if [ "$response" = "y" ]; then
-		eval $1 && eval $2 && eval $3
-		printf "\n ✓ Done."
-		let steps_complete++
+		if eval $1 && eval $2 && eval $3; then
+			printf "\n ✓ Done."
+			let steps_complete++
+			return 0
+		else
+			printf "\n X Failed!"
+			return 1
+		fi
 	elif [ "$response" = "s" ]; then
 		printf "\n Step $(( $steps - 1 )) skipped."
-		return
+		return 0
 	else
 		read -n 1 -p " Step $(( $steps - 1 )) aborted. Do you really want to quit? ([y]es, [N]o) " abort
 		if [ "$abort" = "y" ]; then
@@ -161,8 +166,19 @@ run_command () {
 			exit 0
 		else
 			printf "\n Step $(( $steps - 1 )) aborted. Continuing...\n"
-			return
+			return 0
 		fi
+	fi
+}
+
+build_system_type () {
+	if [ -f "configure.ac" -o -f "configure.ac.in" ]; then
+		echo "autotools"
+	elif [ -f "meson.build" ]; then
+		echo "meson"
+	else
+		printf "$warning Unknown build system.\n"
+		return 1
 	fi
 }
 
@@ -241,13 +257,39 @@ update_configure_ac_in () {
 }
 
 get_sha1_hash () {
-	sha1sum $component-$version.tar.bz2 | cut -d ' ' -f 1
+	local suffix
+
+	if [ "$1" = "autotools" ]; then
+		suffix=bz2
+	elif [ "$1" = "meson" ]; then
+		suffix=xz
+	fi
+
+	sha1sum "$component-$version.tar.$suffix" | cut -d ' ' -f 1
+}
+
+join_by () {
+	local delim="${1-}" first="${2-}"
+	if shift 2; then
+		printf '%s' "$first" "${@/#/$delim}"
+	fi
 }
 
 # Playbook for all release steps
 run_steps () {
-	step "Update configure.ac.in \e[0m(add new version and remove git tag)"
-	run_command "update_configure_ac_in pre"
+	local build_type
+	local dist_commands
+	local build_tarball_prompt
+
+	build_type=$(build_system_type)
+	if [ -z "$build_type" ]; then
+		return 1
+	fi
+
+	if [ "$build_type" = "autotools" ]; then
+		step "Update configure.ac.in \e[0m(add new version and remove git tag)"
+		run_command "update_configure_ac_in pre"
+	fi
 
 	step "Update NEWS file with changelog? \e[0m(xfce-update-news)"
 	run_command "xfce-update-news $component $version"
@@ -258,23 +300,37 @@ run_steps () {
 		run_command "update_appdata_file $appdata_file"
 	fi
 
-	step "Build the tarball \e[0m(./autogen.sh && $MAKE -j$nproc distcheck)"
-	# either in the xfce-build or xfce-test container or on the local machine
-	if [ -n "$TAG" ]; then
-		if [[ "$TAG" == "xfce-build" ]]; then
-			run_command "xfce-build"
-		else
-			run_command "xfce-test call ./autogen.sh" "xfce-test call $MAKE -j$nproc distcheck"
-		fi
-	else
-		run_command "./autogen.sh" "$MAKE -j$nproc distcheck"
-	fi
-
 	step "Commit the changes \e[0m(git add -u; git commit -m 'Updates for release')"
 	run_command "git add -u" "git commit -m 'Updates for release'"
 
 	step "Tag the version \e[0m(git tag -a $component-$version)"
 	run_command 'git tag -a $component-$version -e -m "$(xfce-update-news $component $version WRITETAG)"'
+
+	if [ "$build_type" = "autotools" ]; then
+		build_tarball_prompt="Build the tarball \e[0m(./autogen.sh && $MAKE -j$nproc distcheck)"
+		dist_commands=("./autogen.sh" "$MAKE -j$nproc distcheck")
+	elif [ "$build_type" = "meson" ]; then
+		build_tarball_prompt="Build the tarball \e[0m(meson setup && meson dist --include-subprojects)"
+		dist_commands=("rm -rf build" "meson setup build" "meson dist -C build ")
+	fi
+
+	# either in the xfce-build or xfce-test container or on the local machine
+	if [[ "$TAG" == "xfce-build" ]]; then
+		# turn the array into a single argument to pass to 'xfce-build',
+		# stripping any '-j' arguments
+		dist_commands=("xfce-build $(join_by ' \&\& ' "${dist_commands[@]}" | sed -e 's/-j[0-9]*//')")
+	elif [ -n "$TAG" ]; then
+		# prefix each element with 'xfce-test call '
+		dist_commands=("${dist_commands[@]/#/xfce-test call }")
+	fi
+
+	step "$build_tarball_prompt"
+	if ! run_command "${dist_commands[@]}"; then
+		printf "\n\nDeleting tag and rolling back release commit.\n"
+		git tag -d $component-$version
+		git reset --hard HEAD^
+		return 1
+	fi
 
 	step "Push your changes \e[0m(git push && git push --tags)"
 	run_command "git push" "git push --tags"
@@ -283,10 +339,12 @@ run_steps () {
 	run_command "exo-open 'https://releases.xfce.org/'"
 
 	step "Click on 'Release New Version' \e[0m(https://releases.xfce.org/project/$component/new-release/tarball)"
-	run_command "exo-open 'https://releases.xfce.org/project/$component/new-release/tarball?checksum=$(get_sha1_hash)'"
+	run_command "exo-open 'https://releases.xfce.org/project/$component/new-release/tarball?checksum=$(get_sha1_hash $build_type)'"
 
-	step "Add the git back to version_tag() in configure.ac.in"
-	run_command "update_configure_ac_in post"
+	if [ "$build_type" = "autotools" ]; then
+		step "Add the git back to version_tag() in configure.ac.in"
+		run_command "update_configure_ac_in post"
+	fi
 
 	step "Commit and push the change \e[0m(git add -u; git commit -m 'Back to development'; git push)"
 	run_command "git add -u" "git commit -m 'Back to development'" "git push"
@@ -297,7 +355,7 @@ run_steps () {
 main () {
 	sanity_checks
 	test_parameters $component $version
-	run_steps
+	run_steps || exit 1
 
 	printf "\nCongrats, you completed $steps_complete of $steps steps of doing a release for Xfce!\n"
 }
