Use 'git describe' to get the version number for meson

diff --git a/meson-project-template/print-version b/meson-project-template/print-version
--- a/meson-project-template/print-version
+++ b/meson-project-template/print-version
@@ -8,13 +8,18 @@ else
     cd "$(dirname $0)"
 fi
 
-if [ ! -r version ]; then
-    echo "No 'version' file found in source root, or file unreadable" >&2
-    exit 1
-elif [ "$(tail -n 1 version)" = "git" ]; then
-    version=$(head -n 1 version)
+desc=$(git describe 2>/dev/null || true)
+
+if [ -z "$desc" ]; then
     gitrev=$(git rev-parse --short HEAD 2>/dev/null || echo "UNKNOWN")
-    echo "${version}git-${gitrev}"
+    version="0.1.0git-${gitrev}"
+elif [[ $desc =~ ([0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?)-[0-9]+-g([0-9a-f]+)$ ]]; then
+    version="${BASH_REMATCH[1]}git-${BASH_REMATCH[3]}"
+elif [[ $desc =~ ([0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?)$ ]]; then
+    version="${BASH_REMATCH[1]}"
 else
-    head -n 1 version
+    echo "Unable to parse 'git describe' output" >&2
+    exit 1
 fi
+
+echo "$version"
